### ISSUE TITLE
Feature: Drain number of nodes at a time

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/elasticsearch-drain#24]
Elasticsearch is having performance issues when a whole ASG of nodes is drained at once while there are consistent write operations being made to the cluster. We should be able to drain a randomly sampled number of nodes in an ASG at a time, then sample the remaining nodes again and again until the ASG is empty.

Additionally, this feature needs to respect nodes that are currently being drained (in the exclusion list) and still exist in the ASG. Those nodes should be operated on **first** if the drain script fails or is exited.

**Comment by athompson-r7** [comment]
Fixed in #27
